openehr_server:
  hostname: 'localhost'
  port : 8080
  user: 'ehrbase-user'
  password: 'SuperSecretPassword'

bbmri:
  directory_data: './openehr/destinations/bbmri_directory/resources/eu_bbmri_eric_directory_acceptance_server.xlsx'
  csv_input_dir: './csv_in'
  fact_output_dir: './openehr/destinations/bbmri_directory/out'
  directory_with_fact_file_name: 'eu_bbmri_eric_directory_acceptance_server_with_fact.xlsx'
  csv_output_dir: './csv_out'

fact:
  number_of_asterisks: 34
